from pydantic import BaseModel, Field, model_validator
from typing import Optional
from datetime import datetime


class RentBase(BaseModel):
    vehicle_id: str
    start_date: datetime
    end_date: datetime
    pickup_option: str = "self_pickup"
    delivery_address: Optional[str] = None
    insurance_plan: str = "basic"
    child_seat_count: int = 0
    note: Optional[str] = None


class RentCreate(RentBase):
    """Payload used when creating a rent record.

    `rentid` is always auto-generated by the database; clients must not
    supply it. The `renter_uid` is taken from the authenticated user.
    """
    owner_uid: str


class RentUpdate(BaseModel):
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    pickup_option: Optional[str] = None
    delivery_address: Optional[str] = None
    insurance_plan: Optional[str] = None
    child_seat_count: Optional[int] = None
    note: Optional[str] = None

    @model_validator(mode="after")
    def check_at_least_one(cls, values):
        if not values.model_dump(exclude_unset=True):
            raise ValueError("At least one field must be provided for update")
        return values


class Rent(RentBase):
    rentid: str = Field(alias="_id")
    renter_uid: str
    owner_uid: str

    class Config:
        populate_by_name = True
        json_schema_extra = {
            "example": {
                "rentid": "rent_12345",
                "renter_uid": "FirebaseUID_renter",
                "owner_uid": "FirebaseUID_owner",
                "vehicle_id": "veh_12345",
                "start_date": "2026-01-07T09:00:00Z",
                "end_date": "2026-01-08T09:00:00Z",
                "pickup_option": "self_pickup",
                "delivery_address": None,
                "insurance_plan": "basic",
                "child_seat_count": 0,
                "note": "Please keep fuel full.",
            }
        }
